
# SEO settings
title: "Nu-"
title2: "Analytics" # default: ""
description: "Made-to-measure Data Science"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://nu-analytics.github.io # site url
# baseurl: "/" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://avatars0.githubusercontent.com/u/16263296?v=3&s=200


google_analytics: UA-XXXXX-XX
repo: http://github.com/nu-analytics/nu-analytics.github.io
disqus_shortname: ""
twitter_username: ""
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nu-Analytics"
  job      : "A Made to Measure Data Science Team"
  bio      : ""
  thumb    : https://avatars0.githubusercontent.com/u/16263296?v=3&s=200.jpg
  email    : kylenpayne@gmail.com
  url      : http://nu-analytics.github.io
  github   : http://github.com/nu-analytics
  twitter  : 
  facebook : 
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
